services:
  evmit-app:
    build: .
    container_name: evmit-bot
    ports:
      - ${APP_PORTS}
    restart: always
    working_dir: /app
    env_file:
      - .env
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DRIVER_CLASS_NAME: ${DB_DRIVER_CLASS_NAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      - evmit-db

  evmit-db:
    image: ${DB_IMAGE}
    container_name: evmit_db
    ports:
      - ${DB_PORTS}
    environment:
      POSTGRES_DB: evmit_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

networks:
  default:
    name: evmit-bot-network
