server:
  port: 8080
spring:
  application:
    name: EVMitTestTask
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
    enabled: true
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
logging:
  level:
    root: info
    org:
      springframework:
        security: info
#      hibernate:
#        stat: debug
#        type: trace
#    sql: trace
    web: info

