server:
  port: 8080
spring:
  application:
    name: EVMitTestTask
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
logging:
  level:
    root: info
    org:
      springframework:
        security: info
#      hibernate:
#        stat: debug
#        type: trace
#    sql: trace
    web: info

